pool_fee_discount = 0.0
pool_identity_address = "i9M3xxQNktYcpRTp5KJzjJCtiuShrU2D5w"
currencyid = "i776Hug8UKzoV39sivL23D4cKDemrUgnP7"
currencyidhex = "b1a8a058babf898f34f5241a7508ec250cc8d227"
default_pool_fee = 0.05
default_min_payout = 800000000
default_tx_fee = 10000
name = "vrsctest"
payout_interval = 1800
rpc_password = "password"
rpc_port = 20021
rpc_user = "username"
testnet = true
zmq_port_blocknotify = 20023
